unit TestuWebServices;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, uWebServices;

type
  // Test methods for class TWebServices

  TestTWebServices = class(TTestCase)
  strict private
    FWebServices: TWebServices;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCep;
    procedure TesteCurrencyConvertor;
  end;

implementation

procedure TestTWebServices.SetUp;
begin
  FWebServices := TWebServices.Create;
end;

procedure TestTWebServices.TearDown;
begin
  FWebServices.Free;
  FWebServices := nil;
end;

procedure TestTWebServices.TestCep;
var Endereco : String;
begin
    Endereco := 'Rua São Francisco Xavier - até 278 - lado par, Tijuca, Rio de Janeiro, RJ, 3304557';
    CheckEqualsString(Endereco,FWebServices.Cep[20550012],'');
end;

procedure TestTWebServices.TesteCurrencyConvertor;
begin
    CheckNotEquals( 0, FWebServices.ConversorDolarReal);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTWebServices.Suite);
end.

