unit TestuFormatador;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

   uses
      TestFramework, uTipos, uFormatador;

   type
      // Test methods for class TFormatador

      TestTFormatador = class( TTestCase )
      strict private
         FFormatador: TFormatador;
      public
         procedure SetUp; override;
         procedure TearDown; override;
      published
         procedure TestLimpar;
         procedure TestMascarar;
         procedure TestColocaMascara;
         procedure TestRetiraMascara;
      end;

implementation

   uses
      System.SysUtils, System.Classes, System.Character,
  System.Generics.Collections;

   procedure TestTFormatador.SetUp;
   begin
      FFormatador := TFormatador.Create;
   end;

   procedure TestTFormatador.TearDown;
   begin
      FFormatador.Free;
      FFormatador := nil;
   end;

   procedure TestTFormatador.TestLimpar;
   var
      ReturnValue: string;
      pTexto     : string;
   begin
      pTexto := 'TEXTO';
      // TODO: Setup method call parameters
      ReturnValue := FFormatador.Limpar( pTexto );
      // TODO: Validate method results
      CheckEqualsString( EmptyStr, ReturnValue, 'Valor do Retorno ' + ReturnValue );
   end;

   procedure TestTFormatador.TestMascarar;
   var
      ReturnValue   : string;
      Mascara       : string;
      Texto         : string;
      pTipoDocumento: TTipoDoc;
      Aux           : Boolean;
   begin
      Aux                := True;
      for pTipoDocumento := tpCPF to tpTelefoneDDD do
         begin
            Mascara := FFormatador.Mascara[ pTipoDocumento ];
            Texto   := TFormatador.RetiraMascara( Mascara );
            // TODO: Setup method call parameters
            ReturnValue := FFormatador.Mascarar( Texto, Mascara );
            // TODO: Validate method results
            Aux := Aux and SameText( Mascara, ReturnValue );
            if not Aux then
               break;
         end;
      Assert( Aux, 'Valor do Retorno ' + ReturnValue );
   end;

   procedure TestTFormatador.TestColocaMascara;
   var
      ReturnValue   : string;
      Mascara       : string;
      Texto         : string;
      pTipoDocumento: TTipoDoc;
      Aux           : Boolean;
   begin
      Aux                := True;
      for pTipoDocumento := tpCPF to tpTelefoneDDD do
         begin
            Mascara := FFormatador.Mascara[ pTipoDocumento ];
            Texto   := TFormatador.RetiraMascara( Mascara );
            // TODO: Setup method call parameters
            ReturnValue := TFormatador.ColocaMascara( pTipoDocumento, Texto );
            // TODO: Validate method results
            Aux := Aux and SameText( Mascara, ReturnValue );
            if not Aux then
               break;
         end;
      Assert( Aux, 'Valor do Retorno ' + ReturnValue );
   end;

   procedure TestTFormatador.TestRetiraMascara;
   var
      ReturnValue: string;
      pString    : string;
   begin
      pString := '123.456.789-00';
      // TODO: Setup method call parameters
      ReturnValue := TFormatador.RetiraMascara( pString );
      // TODO: Validate method results
      CheckEqualsString( '12345678900', ReturnValue, 'Valor do Retorno ' + ReturnValue );
   end;

initialization

   // Register any test cases with the test runner
   RegisterTest( TestTFormatador.Suite );

end.
